// This is free and unencumbered software released into the public domain.
// 
// Anyone is free to copy, modify, publish, use, compile, sell, or
// distribute this software, either in source code form or as a compiled
// binary, for any purpose, commercial or non-commercial, and by any
// means.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

///////////////////////////////////////////////////////////////////////////////
// (mab) Trend
//
// This indicator is a trend detection tool that uses a combination of moving 
// averages and supertrend to determine the current market trend.
//
// Version: 2.0
///////////////////////////////////////////////////////////////////////////////


//@version=6
indicator('(mab) Trend', shorttitle='(mab)Trend', overlay=true)

// (mab) Colors
col_none = color.new(color.white, 100)

col_darkSpringGreen 			= #137547
col_lightGreen 					= #8fe388
col_rubyRed 					= #931621
col_redPigment 					= #ef1010
col_outrageousOrange 			= #fc7753
col_mysticMaroon 				= #bc387d
col_darkBluePurple 				= #311b92
col_trurfsBlue 					= #0091eb
col_honoluluBlue 				= #176da3
col_GreenBlueCrayola 			= #1e91d6
col_vividSkyBlue 				= #42cafd
col_maximumYellowRed 			= #fec149
col_navajo_white 				= #FEDB9B
col_seeshell 					= #fef4ec

col_blue1 						= #CFEAF1
col_blue2 						= #BBD2E7
col_blue3 						= #A6BADC
col_blue4 						= #92A2D2
col_blue5 						= #7D8AC7
col_blue6 						= #6972BD
col_blue7 						= #545AB2
col_blue8 						= #4042A8
col_blue9 						= #2B2A9D


//////////////////////////////////
// General settings and enable/disable indicators
//////////////////////////////////
source 							= input.source(close, title='Input', group='General')
trendMode						= input.string('MA', title='Trend detection mode', options=['MA', 'Supertrend', 'Supertrend and MA', 'ADX & DI'], group='General')	
showMa 							= input.bool(true, title='Show SMA', group='General')
showSuperTrend 					= input.bool(false, title='Show Super Trend indicator', group='General')


//////////////////////////////////
// MA
//////////////////////////////////
ma1Length						= input.int(13, title='MA length', minval=1, group = 'MA')
ma1Mode							= input.string('EMA', title='SMA / EMA', options=['SMA', 'EMA'], group = 'MA')
ma2Length						= input.int(30, title='SMA length', minval=1, group = 'MA')
ma2Mode							= input.string('SMA', title='SMA / EMA', options=['SMA', 'EMA'], group = 'MA')


// Calculate SMA 
ma1 = ma1Mode == 'SMA' ? ta.sma(source, ma1Length) : ta.ema(source, ma1Length)
ma2 = ma2Mode =='SMA' ? ta.sma(source, ma2Length) : ta.ema(source, ma2Length)
isMaBullish = ma1 > ma2
isMa2Ascending = ma2 > ma2[1]

// Plot EMA's and SMA's
plot(showMa ? ma1 : na, title='MA 1', color=color.new(col_rubyRed, 0), style=plot.style_line, linewidth=1)
plot(showMa ? ma2 : na, title='MA 2', color=color.new(col_darkSpringGreen, 0), style=plot.style_line, linewidth=1)



//////////////////////////////////
// Supertrend
//////////////////////////////////
stFastAtrPeriod 					= input.int(10, title='Fast ATR period', minval=1, group='Supertrend')
stFastAtrMultiplier 				= input.float(3.0, title='Fast ATR multiplier', minval=0.1, group='Supertrend')
stSlowAtrPeriod 					= input.int(30, title='Slow ATR period', minval=1, group='Supertrend')
stSlowAtrMultiplier 				= input.float(9.0, title='Slow ATR multiplier', minval=0.1, group='Supertrend')

// Calculate fast Supertrend
stFastUp = hl2 - stFastAtrMultiplier * ta.atr(stFastAtrPeriod)
stFastUp1 = nz(stFastUp[1], stFastUp)
stFastUp := close[1] > stFastUp1 ? math.max(stFastUp, stFastUp1) : stFastUp

stFastDown = hl2 + stFastAtrMultiplier * ta.atr(stFastAtrPeriod)
stFastDown1 = nz(stFastDown[1], stFastDown)
stFastDown := close[1] < stFastDown1 ? math.min(stFastDown, stFastDown1) : stFastDown

isStFastBullish = true
isStFastBullish := nz(isStFastBullish[1], isStFastBullish)
isStFastBullish := not isStFastBullish and close > stFastDown1 ? true : isStFastBullish and close < stFastUp1 ? false : isStFastBullish

// Calculate slow Supertrend
stSlowUp = hl2 - stSlowAtrMultiplier * ta.atr(stSlowAtrPeriod)
stSlowUp1 = nz(stSlowUp[1], stSlowUp)
stSlowUp := close[1] > stSlowUp1 ? math.max(stSlowUp, stSlowUp1) : stSlowUp

stSlowDown = hl2 + stSlowAtrMultiplier * ta.atr(stSlowAtrPeriod)
stSlowDown1 = nz(stSlowDown[1], stSlowDown)
stSlowDown := close[1] < stSlowDown1 ? math.min(stSlowDown, stSlowDown1) : stSlowDown

isStSlowBullish = true
isStSlowBullish := nz(isStSlowBullish[1], isStSlowBullish)
isStSlowBullish := not isStSlowBullish and close > stSlowDown1 ? true : isStSlowBullish and close < stSlowUp1 ? false : isStSlowBullish


// Plot Supertrend
stFastBullPlot = plot(showSuperTrend and isStFastBullish ? stFastUp : na, title='Fast ST up trend', style=plot.style_linebr, linewidth=1, color=color.new(col_lightGreen, 0))
stFastBearPlot = plot(showSuperTrend and not isStFastBullish ? stFastDown : na, title='Fast ST down trend', style=plot.style_linebr, linewidth=1, color=col_outrageousOrange)
stSlowBullPlot = plot(showSuperTrend and isStSlowBullish ? stSlowUp : na, title='Slow ST up trend', style=plot.style_linebr, linewidth=1, color=color.new(col_lightGreen, 0))
stSlowBearPlot = plot(showSuperTrend and not isStSlowBullish ? stSlowDown : na, title='Slow ST down trend', style=plot.style_linebr, linewidth=1, color=col_outrageousOrange)



//////////////////////////////////
// ADX, DI
//////////////////////////////////
adxDiLength = input(14)
adxThreshold = input(20)

tR = math.max(math.max(high-low, math.abs(high-nz(close[1]))), math.abs(low-nz(close[1])))
dMPlus = high-nz(high[1]) > nz(low[1])-low ? math.max(high-nz(high[1]), 0): 0
dMMinus = nz(low[1])-low > high-nz(high[1]) ? math.max(nz(low[1])-low, 0): 0

smoothTR = 0.0
smoothTR := nz(smoothTR[1]) - (nz(smoothTR[1])/adxDiLength) + tR

smoothDMPlus = 0.0
smoothDMPlus := nz(smoothDMPlus[1]) - (nz(smoothDMPlus[1])/adxDiLength) + dMPlus

smoothDMMinus = 0.0
smoothDMMinus := nz(smoothDMMinus[1]) - (nz(smoothDMMinus[1])/adxDiLength) + dMMinus

DIPlus = smoothDMPlus / smoothTR * 100
DIMinus = smoothDMMinus / smoothTR * 100
DX = math.abs(DIPlus-DIMinus) / (DIPlus+DIMinus)*100
ADX = ta.sma(DX, adxDiLength)



//////////////////////////////////
// Trend
//////////////////////////////////
isBullTrend = false
isBearTrend = false

if trendMode == 'MA'
    isBullTrend := isMaBullish and isMa2Ascending
	isBearTrend := not isMaBullish and not isMa2Ascending
else if trendMode == 'Supertrend'
    isBullTrend := isStFastBullish and isStSlowBullish
	isBearTrend := not isStFastBullish and not isStSlowBullish
else if trendMode == 'Supertrend and MA'
    isBullTrend := isMaBullish and isMa2Ascending and isStFastBullish
    isBearTrend := not isMaBullish and not isMa2Ascending and not isStFastBullish
else if trendMode == 'ADX & DI'
    isBullTrend := DIPlus > DIMinus and ADX > adxThreshold
	isBearTrend := DIMinus > DIPlus and ADX > adxThreshold

// Plot background trend color
bgcolor(isBullTrend ? color.new(col_darkSpringGreen, 80) : na)
bgcolor(isBearTrend ? color.new(col_rubyRed, 80) : na)



