// This is free and unencumbered software released into the public domain.
// 
// Anyone is free to copy, modify, publish, use, compile, sell, or
// distribute this software, either in source code form or as a compiled
// binary, for any purpose, commercial or non-commercial, and by any
// means.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

///////////////////////////////////////////////////////////////////////////////
// (mab) Trend
//
// This indicator is a trend detection tool that uses a combination of moving 
// averages and supertrend to determine the current market trend.
//
// Version: 2.0
///////////////////////////////////////////////////////////////////////////////


//@version=5
indicator('(mab) Trend', shorttitle = '(mab)Trend', overlay = true)

// (mab) Colors
col_none = color.new(color.white, 100)

col_darkSpringGreen = #137547
col_lightGreen = #8fe388
col_rubyRed = #931621
col_redPigment = #ef1010
col_outrageousOrange = #fc7753
col_mysticMaroon = #bc387d
col_darkBluePurple = #311b92
col_trurfsBlue = #0091eb
col_honoluluBlue = #176da3
col_GreenBlueCrayola = #1e91d6
col_vividSkyBlue = #42cafd
col_maximumYellowRed = #fec149
col_navajo_white = #FEDB9B
col_seeshell = #fef4ec

col_blue1 = #CFEAF1
col_blue2 = #BBD2E7
col_blue3 = #A6BADC
col_blue4 = #92A2D2
col_blue5 = #7D8AC7
col_blue6 = #6972BD
col_blue7 = #545AB2
col_blue8 = #4042A8
col_blue9 = #2B2A9D


//////////////////////////////////
// General settings and enable/disable indicators
//////////////////////////////////
source = input.source(close, title = 'Input', group = 'General')
trendMode = input.string('MA Crossover', title = 'Trend detection mode', 
  options = [ 'MA Crossover', 'MA Slope', 'MA Crossover and Slope', 'Supertrend', 'Supertrend on MA' ], 
  group = 'General')
showMa = input.bool(true, title = 'Show MA', group = 'General')
showSuperTrend = input.bool(false, title = 'Show Super Trend indicator', 
  group = 'General')


//////////////////////////////////
// MA
//////////////////////////////////
ma1Length = input.int(13, title = 'Fast MA length', minval = 1, group = 'MA')
ma1Mode = input.string('EMA', title = 'SMA / EMA', options = ['SMA', 'EMA'], group = 'MA')
ma2Length = input.int(30, title = 'Slow MA length', minval = 1, group = 'MA')
ma2Mode = input.string('SMA', title = 'SMA / EMA', options = ['SMA', 'EMA'], group = 'MA')


// Calculate MA 
ma1 = ma1Mode == 'SMA' ? ta.sma(source, ma1Length) : ta.ema(source, ma1Length)
ma2 = ma2Mode == 'SMA' ? ta.sma(source, ma2Length) : ta.ema(source, ma2Length)
isMaBullish = ma1 > ma2
isMa1Ascending = (ma1 > ma1[1])
isMa2Ascending = (ma2 > ma2[1])
isMa2Below = ma2 < source

// Plot EMA's and SMA's
plot(showMa ? ma1 : na, title = 'Fast MA', color = color.new(col_rubyRed, 0), style = plot.style_line, linewidth = 1)
plot(showMa ? ma2 : na, title = 'Slow MA', color = color.new(col_darkSpringGreen, 0), style = plot.style_line, linewidth = 1)


//////////////////////////////////
// Supertrend
//////////////////////////////////
stAtrPeriod = input.int(10, title = 'ATR period', minval = 1, group = 'Supertrend')
stAtrMultiplier = input.float(3.0, title = 'ATR multiplier', minval = 0.1, group = 'Supertrend')

stSource1 = trendMode == 'Supertrend on MA' ? ma2 : hl2
stSource2 = trendMode == 'Supertrend on MA' ? ma2 : close

// Calculate fast Supertrend
stUp = stSource1 - stAtrMultiplier * ta.atr(stAtrPeriod)
stUp1 = nz(stUp[1], stUp)
stUp := stSource2[1] > stUp1 ? math.max(stUp, stUp1) : stUp

stDown = stSource1 + stAtrMultiplier * ta.atr(stAtrPeriod)
stDown1 = nz(stDown[1], stDown)
stDown := stSource2[1] < stDown1 ? math.min(stDown, stDown1) : stDown

isstBullish = true
isstBullish := nz(isstBullish[1], isstBullish)
isstBullish := not isstBullish and stSource2 > stDown1 ? true : isstBullish and stSource2 < stUp1 ? false : isstBullish

// Plot Supertrend
plot(showSuperTrend and isstBullish ? stUp : na, title = 'Fast ST up trend', style = plot.style_linebr, linewidth = 1, color = color.new(col_lightGreen, 0))
plot(showSuperTrend and not isstBullish ? stDown : na, title = 'Fast ST down trend', style = plot.style_linebr, linewidth = 1, color = col_outrageousOrange)


//////////////////////////////////
// ADX, DI
//////////////////////////////////


//////////////////////////////////
// Trend
//////////////////////////////////
isBullTrend = false
isBearTrend = false

if trendMode == 'MA Crossover'
    isBullTrend := isMaBullish
    isBearTrend := not isMaBullish
else if trendMode == 'MA Slope'
    isBullTrend := (isMa2Ascending and isMa2Below) or (isBullTrend[1] and (isMa2Ascending or isMa2Below))
    isBearTrend := (not isMa2Ascending and not isMa2Below) or (isBearTrend[1] and (not isMa2Ascending or not isMa2Below))
else if trendMode == 'MA Crossover and Slope'
    isBullTrend := (isMaBullish and isMa1Ascending and isMa2Ascending) or (isBullTrend[1] and (isMaBullish or isMa1Ascending or isMa2Ascending))
    isBearTrend := (not isMaBullish and not isMa1Ascending and not isMa2Ascending) or (isBearTrend[1] and (not isMaBullish or not isMa1Ascending or not isMa2Ascending))
else if trendMode == 'Supertrend'
    isBullTrend := isstBullish
    isBearTrend := not isstBullish
else if trendMode == 'Supertrend on MA'
    isBullTrend := isstBullish
    isBearTrend := not isstBullish

// Plot background trend color
bgcolor(isBullTrend ? color.new(col_darkSpringGreen, 80) : na)
bgcolor(isBearTrend ? color.new(col_rubyRed, 80) : na)
